[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
identity_core = "idcore1111111111111111111111111111111111"
credential_vault = "credvault1111111111111111111111111111"

[programs.devnet]
identity_core = "idcore1111111111111111111111111111111111"
credential_vault = "credvault1111111111111111111111111111"

[programs.mainnet]
identity_core = "idcore1111111111111111111111111111111111"
credential_vault = "credvault1111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
